### ISSUE TITLE
[TRACKING] ViewComponent documentation site

### ISSUE THREAD

**Issue by joelhawksley** [github/view_component#505]
## Summary

With Rails 6.1 on the horizon, the ViewComponent project will be under increased attention from the public. 

This is a great opportunity for us to make the best first impression possible to the Rails community. 

Let's level up our README into a documentation website we'll be proud of!

## TODO

- [x] Register domain name (`viewcomponent.org`)
- [x] Pick out / design Jekyll template
- [x] Move docs from README to site
- [x] Publish site
- [x] Review site content and plan for any additions
- [x] Add quick start to README (https://github.com/github/view_component/pull/512#pullrequestreview-517923634)

## Open questions

- Should we have a logo? #649 
- What are some documentation sites we might be inspired by?

**Comment by jaredcwhite** [comment]
A few Ruby/Rails-aligned documentation sites I'll mention:

* [StimulusReflex](https://docs.stimulusreflex.com)
* [Jumpstart](https://jumpstartrails.com/docs/)
* [Bridgetown](https://www.bridgetownrb.com) (full disclosure — I work on this one)

**Comment by joelhawksley** [comment]
@jaredcwhite those are all fantastic examples!

I'm really impressed with the Bridgetown site. Would you be up for helping out with this project?

**Comment by jaredcwhite** [comment]
@joelhawksley Well, if you don't mind using Bridgetown rather than Jekyll, I think it'd be pretty easy to clone the BT site and clear out the content and tweak the design for use here. You should be able to use GH actions to run the build process and deploy on pages￼￼ here… slightly more inconvenient than using Jekyll directly, but not by a ton. (Bonus: you get Webpack for front-end assets as well that way…) Anyway, I could help out with all that if need be.

**Comment by g13ydson** [comment]
> A few Ruby/Rails-aligned documentation sites I'll mention:
> 
> * [StimulusReflex](https://docs.stimulusreflex.com)
> * [Jumpstart](https://jumpstartrails.com/docs/)
> * [Bridgetown](https://www.bridgetownrb.com) (full disclosure — I work on this one)

I really like how the Stimulus Reflex documentation works. Very clean, but it's a personal taste 😁

**Comment by g13ydson** [comment]
@joelhawksley I really like how things are organized using the gitbook + github integration. I created a documentation reorganizing some subjects by sessions. So, if it looks good, I can open a PR with the gitbook files.
https://g13ydson.gitbook.io/view-component-docs

**Comment by pinzonjulian** [comment]
I'm happy to help out writing any guides or docs! 

PS: Love the gitbook site @g13ydson !

**Comment by joelhawksley** [comment]
@g13ydson very cool! Would we still be able to host this on GitHub pages?

**Comment by g13ydson** [comment]
@joelhawksley with gitbook it is possible, but it takes more work. I decided to create with Jekyll. #529

**Comment by joelhawksley** [comment]
In https://www.youtube.com/watch?v=EQoJVFgZXo4, @maxshelley gave our docs a thorough read as a developer new to the project ❤️ 

Here are some improvements I think we should look into making based on his experience:

- [ ] Add more detail regarding the `form_for` workaround. I think we can direct folks towards using the `_tag` helpers for now.
- [ ] Provide a better example application experience than `view-component-demo`, which is out of date and lacks documentation.
- [ ] Add documentation for the monkey patch.
- [ ] Add a brief explanation for _why_ ViewComponent is faster than partials.
- [ ] Clarify that `content` is set by passing in a block, and doesn't need to be an argument in the component initializer.
- [ ] Add documentation on how to generate a sidecar folder with the generator.
- [ ] Clarify that `render?` is for whether the _entire_ component is rendered or not.
- [ ] Find a better way to explain what is accessible from the component template (instance variables and methods on the component object).

**Comment by joelhawksley** [comment]
Some resources I plan to reference for this work:

https://github.com/reduxjs/redux/issues/3609
https://documentation.divio.com
https://news.ycombinator.com/item?id=21289832
https://stoplight.io/blog/writing-documentation-when-you-arent-a-technical-writer-part-one-ef08a09870d1/
https://stoplight.io/blog/writing-documentation-when-you-arent-a-technical-writer-part-two-59997587cc2a/
https://news.ycombinator.com/item?id=17829751
https://brainhub.eu/blog/writing-good-documentation-open-source-library/
https://dev.to/ojkelly/the-four-layers-to-great-documentation-dj7
https://jacobian.org/series/great-documentation/
https://v3.vuejs.org/guide/contributing/writing-guide.html

**Comment by Spone** [comment]
I'm starting an evolving list of wanted improvements to the docs:

- [ ] explain the use cases for variants, and how to use the feature in regular components
- [ ] [...]

**Comment by joelhawksley** [comment]
Some notes from https://github.com/github/view_component/pull/684:

- [ ] Add a diagram like https://twitter.com/dan_abramov/status/981712092611989509/photo/1 to the Lifecycle page.
- [ ] Add `_after_compile` to Lifecycle.

**Comment by joelhawksley** [comment]
> I'm starting an evolving list of wanted improvements to the docs:
> 
> * [ ]  explain the use cases for variants, and how to use the feature in regular components
> * [ ]  [...]

@Spone I've filed this in https://github.com/github/view_component/issues/898 ❤️

**Comment by joelhawksley** [comment]
👋🏻 I've split this issue out into sub-issues 🎊
